/**
 * CMS Content Schema
 * ──────────────────
 * Override at runtime by setting window.CHANGG_CONTENT = { en: {…}, vi: {…} }
 * before the app boots, or via localStorage key 'changg_cms_content' for drafts.
 */

export function resolveContent() {
  if (typeof window !== 'undefined' && window.CHANGG_CONTENT) {
    return window.CHANGG_CONTENT;
  }
  try {
    const draft = localStorage.getItem('changg_cms_content');
    if (draft) return JSON.parse(draft);
  } catch (_) {}
  return DEFAULT_CONTENT;
}

export const DEFAULT_CONTENT = {
  en: {
    nav: {
      logo: 'CHANGG.',
      links: [
        { label: 'About Me',   id: 'about-me'   },
        { label: 'Experience', id: 'experience'  },
        { label: 'Project',    id: 'project'     },
        { label: 'Contact',    id: 'contact'     },
      ],
    },

    hero: {
      eyebrow:    'Content Creator · Ho Chi Minh City',
      titleLines: ['Changg Nguyen', 'tells stories,', 'frame by frame.'],
      sub:        'Content full-stack — from ideas, scripts, to filming & editing. 3 years producing multi-platform content & short films.',
      meta: [
        { label: 'SINCE',     value: '2022' },
        { label: 'PLATFORMS', value: 'FB · TikTok · YouTube' },
        { label: 'BASE',      value: 'Ho Chi Minh City' },
      ],
    },

    about: {
      number: '01',
      title:  'About me',
      sub:    'A few lines about me, my skills & career goals.',
      name:   'Nguyễn Thị Thùy Trang',
      nick:   '"Changg Nguyễn" · Born 2002',
      preface: 'I work content "full-stack" — from when the idea is still on paper to when the product goes live. 3 years revolving around 2 axes: multi-platform content operations (content calendar, script, filming & editing, channel performance tracking at Kafi Securities, Victory Investment, House of Deera) and film/TVC production (10+ projects — from Production Assistant to Producer, Assistant Director). My strength lies in keeping a project on schedule whether I\'m the one holding the camera, writing the script, or coordinating the whole crew behind the scenes.',
      videoId: 'VIDEO_ID',
      basedInLabel:   'Based in',
      basedIn:        'Ho Chi Minh City, Vietnam',
      interestLabel:  'Interests',
      interest:       'Updating...',
      professionalSkillsLabel: 'Professional Skills',
      professionalSkills: [
        'Social Media Management', 'Media Production',
        'Copywriting & Story Writing', 'Photography',
        'Premiere · After Effects · CapCut',
      ],
      softSkillsLabel: 'Soft Skills',
      softSkills: [
        'Communication & Teamwork', 'Presentation',
        'Problem Solving', 'Planning', 'MS Office',
      ],
      goalsLabel: 'Career Goals',
      goals: [
        'Accumulate more experience in Film Production & Content Creation, participate in 5+ projects as Production Assistant / Content Creator',
        'Aim to become a trusted Producer / Content Creator with 30+ projects',
      ],
      educationTag:      "BACHELOR'S DEGREE",
      educationSchool:   'HUTECH University',
      educationMajor:    'Main Major: Film Production · Multimedia',
      educationGpaLabel: 'GPA',
      educationGpa:      '3.06',
      educationStrength: 'Strengths: Media Pre-Production, Content',
      certsLabel: 'Certificates',
      certs: [
        'Advanced Information Technology Applications M3 (2023, HUTECH)',
        'English Proficiency B1 (2023, HUTECH)',
        'Communication and Teamwork Skills (2023, HUTECH)',
      ],
    },

    reels: {
      sectionLabel: 'Best Experience — Selected Reels',
      items: [
        { tag: '01 · 2025—NOW',   title: 'Kafi Securities',    role: 'Content Specialist',  icon: 'video' },
        { tag: '02 · PROJECT',    title: 'Ngọc Thẩm Jewelry',  role: 'Project Manager',     icon: 'check' },
        { tag: '03 · 2024—2025',  title: 'Victory Investment', role: 'Social Media Specialist', icon: 'doc' },
        { tag: '04 · SHORT FILM', title: 'Chữa Chết',          role: 'Producer',            icon: 'play'  },
      ],
    },

    experience: {
      number: '02',
      title:  'Experience Timeline',
      sub:    'Work journey — from social content to media marketing. Click each milestone for details.',
      items: [
        {
          id:   'e1',
          date: '07/2025—Now',
          org:  'Kafi Securities',
          role: 'Content Specialist',
          bullets: [
            'Multi-platform content planning & calendar (Facebook, TikTok)',
            'Script writing for financial & brand content',
            'Video shooting & editing for multiple platforms (Facebook, YouTube, TikTok)',
            'Channel performance tracking & optimisation',
          ],
          slides: 5,
          driveLink:      '#',
          driveLinkLabel: '↗ View campaign drive',
        },
        {
          id:   'e3',
          date: '7/2024—7/2025',
          org:  'Victory Investment Consultant',
          role: 'Social Media Specialist',
          bullets: [
            'TikTok, YouTube content planning & calendar by day/week/month',
            'Creative script writing for TikTok videos',
            'Channel metric tracking, analysis & improvement suggestions',
            'Shoot scheduling: timeline, location, budget, personnel',
            'Video/photo shooting & editing for channels',
          ],
          slides: 5,
          driveLink:      'https://www.tiktok.com/@victory.dinhcu',
          driveLinkLabel: '↗ View TikTok Victory',
        },
        {
          id:   'e5',
          date: '22/01/2024—22/04/2024',
          org:  'Kentary',
          role: 'Media Marketing Intern',
          bullets: [
            'Producing & editing short videos, TVCs, TikTok content for products',
            'Product photography & image retouching',
            'Building marketing strategy, managing marketing team',
          ],
          slides: 5,
          driveLink:      '#',
          driveLinkLabel: '↗ View campaign drive',
        },
        {
          id:   'e4',
          date: '10/2022—10/2023',
          org:  'House of Deera',
          role: 'Beauty Content Creator (Lemon8)',
          bullets: [
            'Building & executing content strategy for beauty channel',
            'Professional photography for cosmetics, skincare, makeup',
            'Image/graphic design for social & content channels',
            'Market insight research, developing new content concepts',
            'Tracking platform trends & algorithms to optimise performance',
          ],
          slides: 5,
          driveLink:      'https://www.lemon8-app.com/changgnguyen?region=vn',
          driveLinkLabel: '↗ View Lemon8 channel',
        },
        {
          id:   'e7',
          date: '7/2022—10/2022',
          org:  'Tùng BT',
          role: 'Editor',
          bullets: [
            'Editing & assembling video from raw footage to finished product',
            'Adding graphics, sound effects, background music',
            'Optimising video for multiple platforms & devices',
            'Managing & organising video files/assets',
          ],
          slides: 5,
          driveLink:      'https://fb.watch/nnOY59ruNw/',
          driveLinkLabel: '↗ View clip',
        },
        {
          id:   'e6',
          date: '5/2022—10/2022',
          org:  'Women Leaders International Networking',
          role: 'Content Intern',
          bullets: [
            'Researching, writing & editing news for leadership board',
            'Building program/event scripts',
            'Designing & producing graphic content for Facebook',
            "Managing & tracking performance of network's social channels",
          ],
          slides: 5,
          driveLink:      'https://www.wlin.com.vn/wlin/business-tour-tham-quan-showroom-nupa-sport-buoi-gap-mat-dac-biet-cua-cac-thanh-vien-wlin-inspire.html',
          driveLinkLabel: '↗ Read article',
        },
      ],
    },

    project: {
      number: '03',
      title:  'Project Timeline',
      sub:    'Short film & TVC projects — Producer, Script Writer, Production Assistant roles.',
      items: [
        {
          id:    'p14',
          date:  '7/2025—6/2026',
          title: 'Series TikTok "Ngọc Thẩm Jewelry"',
          role:  'Project Manager',
          bullets: [
            'Managed pre-production, coordinated personnel, workflow, ensured project timeline and production budget',
            'Worked with clients to ensure production met needs, expectations, and timelines throughout the project',
            'Post-production management: ensuring timeline and client requirements',
          ],
          slides: 5,
          driveLink:      '#',
          driveLinkLabel: '↗ View campaign drive',
        },
        {
          id:    'p4',
          date:  '02/2025—03/2025',
          title: 'TVC Neothera',
          role:  'Production Assistant',
          bullets: [
            'Shoot timeline planning, costume management, casting, budget logistics',
            'On-set support for actors throughout the shoot',
            'Assisted production team handle on-set issues',
          ],
          slides: 5,
          driveLink:      'https://www.facebook.com/NeotheraSkincare/videos/628797779891151',
          driveLinkLabel: '↗ View video',
        },
        {
          id:    'p1',
          date:  '10/2024—12/2024',
          title: 'Short Series TikTok "IRC"',
          role:  'Production Assistant',
          bullets: [
            'Detailed shoot timeline planning, managed entire pre-production',
            'On-set support for actors, ensured shoot schedule',
            'Handled issues throughout production process',
          ],
          slides: 5,
          driveLink:      'https://www.tiktok.com/@ircvietnam/video/7440416635539737876',
          driveLinkLabel: '↗ View clip',
        },
        {
          id:    'p2',
          date:  '06/2024—07/2024',
          title: 'TVC The New Gym',
          role:  'Production Assistant',
          bullets: [
            'Shoot timeline planning, costume management, casting, budget logistics',
            'On-set support for actors throughout the shoot',
            'Assisted production team handle on-set issues',
          ],
          slides: 5,
          driveLink:      'https://youtu.be/4l0Sxzilw8o',
          driveLinkLabel: '↗ View video',
        },
        {
          id:    'p3',
          date:  '04/2024—26/06/2024',
          title: 'Short Film "Trên Đỉnh Đầu"',
          role:  'Production Assistant',
          bullets: [
            'Pre-production: budget, casting, location, wardrobe, crew',
            'Full-time on-set support, handling unexpected issues',
            'Cast care: wardrobe, makeup, catering, rest',
          ],
          slides: 5,
          driveLink:      'https://drive.google.com/file/d/1eyqXdt6qQCf15R4AVxWzKyZMb_UGSFYh/view?usp=drive_link',
          driveLinkLabel: '↗ View drive',
        },
        {
          id:    'p5',
          date:  '05/2024',
          title: 'Short Film "Câu Vọng"',
          role:  'Production Assistant',
          bullets: [
            'Pre-production preparation: budget, casting, wardrobe, timeline, crew',
            'Supported production team throughout shoot',
            "Recorded footage notes, shoot progress & director's notes for post-production",
          ],
          slides: 5,
          driveLink:      'https://youtu.be/cmKXtughTPE',
          driveLinkLabel: '↗ View video',
        },
        {
          id:    'p6',
          date:  '7/2023—28/1/2024',
          title: 'Short Film "Thực"',
          role:  'Producer, Behind The Scene',
          bullets: [
            'Drafted & distributed daily call sheets',
            'Recruited & managed actors, extras',
            'Supported director on-set, managed catering & location',
          ],
          slides: 5,
          driveLink:      'https://www.youtube.com/watch?v=PVonqvdKnzc',
          driveLinkLabel: '↗ View video',
        },
        {
          id:    'p7',
          date:  '12/2023—1/2024',
          title: 'Bona Media',
          role:  'Assistant Director',
          bullets: [
            'Comprehensive on-set director support',
            'Managing actor & crew booking & schedules',
            'Drafting & distributing daily call sheets, production timelines',
          ],
          slides: 5,
          driveLink:      'https://www.youtube.com/@BabyDollTVTiengViet',
          driveLinkLabel: '↗ View channel',
        },
        {
          id:    'p8',
          date:  '27/11—29/11/2023',
          title: 'Short Film "Chuộc"',
          role:  'Production Assistant, BTS, Runner',
          bullets: [
            'Captured activity & interaction images of the film crew',
            'On-set support to ensure smooth production',
            '🏆 Award: Top 10 HUGFIA (HUTECH Graduation Film Award)',
          ],
          slides: 5,
          driveLink:      'https://www.youtube.com/watch?v=a5M-D0n5H-A',
          driveLinkLabel: '↗ View video',
        },
        {
          id:    'p9',
          date:  '25/11/2023',
          title: 'TVC Greenfeed',
          role:  'Production Assistant',
          bullets: [
            'Drafted & distributed daily call sheets',
            'Recruited & managed actors, extras',
            'Supported Producer & PA Leader in on-set operations',
            'Setup & maintained set design',
          ],
          slides: 5,
          driveLink:      'https://www.youtube.com/watch?v=2KTnTb8G8AY',
          driveLinkLabel: '↗ View video',
        },
        {
          id:    'p10',
          date:  '07/2023—12/2023',
          title: 'Short Film "Chữa Chết"',
          role:  'Producer',
          bullets: [
            'Lead pre-production planning for entire project',
            'Budget, casting, vendor & location coordination',
            'Personnel & financial resource management for production',
          ],
          slides: 5,
          driveLink:      'https://drive.google.com/file/d/1y3ds0YhfjJ4zgxffW_36WHqzbg1bVCE0/view?usp=drive_link',
          driveLinkLabel: '↗ View drive',
        },
        {
          id:    'p11',
          date:  '03/2023—05/2023',
          title: 'Short Film "Nơi Em Tìm Thấy Anh"',
          role:  'Script Writer, Producer, BTS',
          bullets: [
            'In charge of pre-production: script development & project planning',
            'Writing & finalising screenplay',
            'Building partnerships, fundraising for the project',
          ],
          slides: 5,
          driveLink:      'https://fb.watch/o386uwQvKz/',
          driveLinkLabel: '↗ View video',
        },
        {
          id:    'p12',
          date:  '03/2023—05/2023',
          title: 'Short Film "Má Bảy Của Tôi"',
          role:  'Behind The Scene, Set Support',
          bullets: [
            'Logistics & support for director, actors, crew during shoot',
            'Capturing high-quality behind-the-scene imagery',
          ],
          slides: 5,
          driveLink:      'https://www.youtube.com/watch?v=0pHAfruSbkQ',
          driveLinkLabel: '↗ View video',
        },
        {
          id:    'p13',
          date:  '03/2022—05/2022',
          title: 'Short Film "Tôi Ghét Ba"',
          role:  'Assistant Director, BTS',
          bullets: [
            'Ensuring comfort for director, actors, crew throughout filming',
            'Building time-management & resource skills, supporting director',
            'Capturing behind-the-scene imagery for media',
          ],
          slides: 5,
          driveLink:      'https://fb.watch/o3849ihxVw/',
          driveLinkLabel: '↗ View video',
        },
      ],
    },

    contact: {
      number:        '04',
      title:         'Contact',
      ctaLines:      ["Let's make something", 'worth watching.'],
      email:         'trangnguyn123@gmail.com',
      gmailUrl:      'https://mail.google.com/mail/?view=cm&fs=1&to=trangnguyn123@gmail.com',
      linkedinLabel: 'LinkedIn',
      linkedinUrl:   'https://www.linkedin.com/in/changg-nguyen/',
      location:      'Based in Ho Chi Minh City, VN',
    },

    footer: {
      copy: '© 2026 Changg Nguyễn',
      role: 'Content Creator · HCMC',
    },
  },

  vi: {
    nav: {
      logo: 'CHANGG.',
      links: [
        { label: 'Về Tôi',      id: 'about-me'   },
        { label: 'Kinh Nghiệm', id: 'experience'  },
        { label: 'Dự Án',       id: 'project'     },
        { label: 'Liên Hệ',     id: 'contact'     },
      ],
    },

    hero: {
      eyebrow:    'Content Creator · Tp. Hồ Chí Minh',
      titleLines: ['Changg Nguyễn', 'kể chuyện,', 'từng khung hình.'],
      sub:        'Content full-stack — từ ý tưởng, kịch bản, đến quay dựng. 3 năm sản xuất nội dung đa nền tảng & phim ngắn.',
      meta: [
        { label: 'TỪ NĂM',   value: '2022' },
        { label: 'NỀN TẢNG', value: 'FB · TikTok · YouTube' },
        { label: 'ĐỊA CHỈ',  value: 'Tp. Hồ Chí Minh' },
      ],
    },

    about: {
      number: '01',
      title:  'Về Tôi',
      sub:    'Vài dòng về mình, năng lực & mục tiêu nghề nghiệp.',
      name:   'Nguyễn Thị Thùy Trang',
      nick:   '"Changg Nguyễn" · Sinh năm 2002',
      preface: 'Mình là người làm content theo kiểu "full-stack" — từ lúc ý tưởng còn trên giấy đến khi sản phẩm lên sóng. 3 năm xoay quanh 2 trục: vận hành nội dung đa nền tảng (content calendar, script, quay dựng, đo hiệu suất kênh tại Kafi Securities, Victory Investment, House of Deera) và sản xuất phim/TVC (đã tham gia 10+ dự án — từ Production Assistant đến Producer, Assistant Director). Thế mạnh của mình nằm ở khả năng giữ một dự án đi đúng tiến độ dù vai trò là người cầm máy, viết kịch bản, hay người đứng sau điều phối cả đoàn.',
      videoId: 'VIDEO_ID',
      basedInLabel:   'Địa điểm',
      basedIn:        'Tp. Hồ Chí Minh, Việt Nam',
      interestLabel:  'Sở thích',
      interest:       'Đang cập nhật',
      professionalSkillsLabel: 'Năng lực chuyên môn',
      professionalSkills: [
        'Social Media Management', 'Media Production',
        'Copywriting & Story Writing', 'Photography',
        'Premiere · After Effects · CapCut',
      ],
      softSkillsLabel: 'Kỹ năng mềm',
      softSkills: [
        'Communication & Teamwork', 'Presentation',
        'Problem Solving', 'Planning', 'MS Office',
      ],
      goalsLabel: 'Mục tiêu nghề nghiệp',
      goals: [
        'Tích lũy thêm kinh nghiệm Sản xuất phim & Content Creation, tham gia 5+ dự án ở vai trò Production Assistant / Content Creator',
        'Hướng đến trở thành Producer / Content Creator được tin tưởng, với 30+ dự án lớn nhỏ',
      ],
      educationTag:      'BẰNG CỬ NHÂN',
      educationSchool:   'Trường Đại học HUTECH',
      educationMajor:    'Ngành chính: Sản xuất phim · Multimedia',
      educationGpaLabel: 'GPA',
      educationGpa:      '3.06',
      educationStrength: 'Thế mạnh: Media Pre-Production, Content',
      certsLabel: 'Chứng chỉ',
      certs: [
        'Ứng dụng CNTT nâng cao M3 (2023, HUTECH)',
        'Tiếng Anh B1 (2023, HUTECH)',
        'Kỹ năng Giao tiếp & Làm việc nhóm (2023, HUTECH)',
      ],
    },

    reels: {
      sectionLabel: 'Kinh Nghiệm Nổi Bật — Tác Phẩm Tiêu Biểu',
      items: [
        { tag: '01 · 2025—NAY',   title: 'Kafi Securities',    role: 'Content Specialist',     icon: 'video' },
        { tag: '02 · DỰ ÁN',      title: 'Ngọc Thẩm Jewelry',  role: 'Project Manager',        icon: 'check' },
        { tag: '03 · 2024—2025',   title: 'Victory Investment', role: 'Social Media Specialist', icon: 'doc'  },
        { tag: '04 · PHIM NGẮN',  title: 'Chữa Chết',          role: 'Nhà Sản Xuất',           icon: 'play'  },
      ],
    },

    experience: {
      number: '02',
      title:  'Lịch Sử Kinh Nghiệm',
      sub:    'Hành trình làm việc — từ content social đến media marketing. Nhấp vào từng mốc để xem chi tiết.',
      items: [
        {
          id:   'e1',
          date: '07/2025—Nay',
          org:  'Kafi Securities',
          role: 'Content Specialist',
          bullets: [
            'Content planning & calendar đa nền tảng (Facebook, TikTok)',
            'Script writing cho nội dung tài chính & thương hiệu',
            'Quay dựng video, edit cho đa nền tảng (Facebook, YouTube, TikTok)',
            'Theo dõi hiệu suất kênh, đề xuất tối ưu',
          ],
          slides: 5,
          driveLink:      '#',
          driveLinkLabel: '↗ View campaign drive',
        },
        {
          id:   'e3',
          date: '7/2024—7/2025',
          org:  'Victory Investment Consultant',
          role: 'Social Media Specialist',
          bullets: [
            'Lên kế hoạch & content calendar TikTok, YouTube theo ngày/tuần/tháng',
            'Viết script sáng tạo cho video TikTok',
            'Theo dõi, phân tích chỉ số kênh và đề xuất hướng cải thiện',
            'Tổ chức lịch quay: timeline, location, budget, nhân sự',
            'Quay, chụp & edit video/hình ảnh cho kênh',
          ],
          slides: 5,
          driveLink:      'https://www.tiktok.com/@victory.dinhcu',
          driveLinkLabel: '↗ Xem TikTok Victory',
        },
        {
          id:   'e5',
          date: '22/01/2024—22/04/2024',
          org:  'Kentary',
          role: 'Media Marketing Intern',
          bullets: [
            'Sản xuất & edit video ngắn, TVC, content TikTok cho sản phẩm',
            'Chụp ảnh sản phẩm & retouch hình ảnh',
            'Xây dựng chiến lược marketing, quản lý marketing team',
          ],
          slides: 5,
          driveLink:      '#',
          driveLinkLabel: '↗ View campaign drive',
        },
        {
          id:   'e4',
          date: '10/2022—10/2023',
          org:  'House of Deera',
          role: 'Beauty Content Creator (Lemon8)',
          bullets: [
            'Xây dựng & triển khai content strategy cho kênh beauty',
            'Sản xuất ảnh chụp chuyên nghiệp cho mỹ phẩm, skincare, makeup',
            'Thiết kế hình ảnh/graphic cho social & kênh nội dung',
            'Nghiên cứu insight thị trường, phát triển concept content mới',
            'Theo dõi xu hướng nền tảng & thuật toán để tối ưu hiệu suất',
          ],
          slides: 5,
          driveLink:      'https://www.lemon8-app.com/changgnguyen?region=vn',
          driveLinkLabel: '↗ Xem kênh Lemon8',
        },
        {
          id:   'e7',
          date: '7/2022—10/2022',
          org:  'Tùng BT',
          role: 'Editor',
          bullets: [
            'Edit & dựng video từ footage thô thành sản phẩm hoàn chỉnh',
            'Thêm graphic, hiệu ứng âm thanh, nhạc nền',
            'Tối ưu video cho nhiều nền tảng & thiết bị khác nhau',
            'Quản lý & sắp xếp file/asset video',
          ],
          slides: 5,
          driveLink:      'https://fb.watch/nnOY59ruNw/',
          driveLinkLabel: '↗ Xem clip',
        },
        {
          id:   'e6',
          date: '5/2022—10/2022',
          org:  'Women Leaders International Networking',
          role: 'Content Intern',
          bullets: [
            'Nghiên cứu, viết & biên tập tin tức cho ban lãnh đạo',
            'Xây dựng kịch bản chương trình/sự kiện',
            'Thiết kế & sản xuất graphic content cho Facebook',
            'Quản lý & theo dõi hiệu suất các kênh social của network',
          ],
          slides: 5,
          driveLink:      'https://www.wlin.com.vn/wlin/business-tour-tham-quan-showroom-nupa-sport-buoi-gap-mat-dac-biet-cua-cac-thanh-vien-wlin-inspire.html',
          driveLinkLabel: '↗ Đọc bài viết',
        },
      ],
    },

    project: {
      number: '03',
      title:  'Lịch Sử Dự Án',
      sub:    'Các dự án phim ngắn & TVC — vai trò Producer, Script Writer, Production Assistant.',
      items: [
        {
          id:    'p14',
          date:  '7/2025—6/2026',
          title: 'Series TikTok "Ngọc Thẩm Jewelry"',
          role:  'Project Manager',
          bullets: [
            'Quản lý tiền kỳ, điều phối nhân sự, workflow, đảm bảo tiến độ và kinh phí sản xuất dự án',
            'Làm việc cùng khách hàng để đảm bảo sản xuất đúng nhu cầu, mong muốn, và đúng thời gian sản xuất xuyên suốt dự án',
            'Quản lý hậu kỳ: đảm bảo đúng tiến độ và đúng yêu cầu từ khách hàng',
          ],
          slides: 5,
          driveLink:      '#',
          driveLinkLabel: '↗ View campaign drive',
        },
        {
          id:    'p4',
          date:  '02/2025—03/2025',
          title: 'TVC Neothera',
          role:  'Production Assistant',
          bullets: [
            'Lên timeline quay, quản lý costume, casting, budget logistics',
            'Hỗ trợ on-set cho diễn viên xuyên suốt buổi quay',
            'Hỗ trợ đoàn sản xuất xử lý phát sinh khi quay',
          ],
          slides: 5,
          driveLink:      'https://www.facebook.com/NeotheraSkincare/videos/628797779891151',
          driveLinkLabel: '↗ Xem video',
        },
        {
          id:    'p1',
          date:  '10/2024—12/2024',
          title: 'Short Series TikTok "IRC"',
          role:  'Production Assistant',
          bullets: [
            'Lên timeline quay chi tiết, quản lý toàn bộ pre-production',
            'Hỗ trợ on-set cho diễn viên, đảm bảo tiến độ quay',
            'Xử lý phát sinh trong suốt quá trình sản xuất',
          ],
          slides: 5,
          driveLink:      'https://www.tiktok.com/@ircvietnam/video/7440416635539737876',
          driveLinkLabel: '↗ Xem clip',
        },
        {
          id:    'p2',
          date:  '06/2024—07/2024',
          title: 'TVC The New Gym',
          role:  'Production Assistant',
          bullets: [
            'Lên timeline quay, quản lý costume, casting, budget logistics',
            'Hỗ trợ on-set cho diễn viên xuyên suốt buổi quay',
            'Hỗ trợ đoàn sản xuất xử lý phát sinh khi quay',
          ],
          slides: 5,
          driveLink:      'https://youtu.be/4l0Sxzilw8o',
          driveLinkLabel: '↗ Xem video',
        },
        {
          id:    'p3',
          date:  '04/2024—26/06/2024',
          title: 'Short Film "Trên Đỉnh Đầu"',
          role:  'Production Assistant',
          bullets: [
            'Pre-production: budget, casting, location, wardrobe, crew',
            'Hỗ trợ on-set toàn thời gian, xử lý sự cố phát sinh',
            'Chăm sóc diễn viên: wardrobe, makeup, catering, nghỉ ngơi',
          ],
          slides: 5,
          driveLink:      'https://drive.google.com/file/d/1eyqXdt6qQCf15R4AVxWzKyZMb_UGSFYh/view?usp=drive_link',
          driveLinkLabel: '↗ View drive',
        },
        {
          id:    'p5',
          date:  '05/2024',
          title: 'Short Film "Câu Vọng"',
          role:  'Production Assistant',
          bullets: [
            'Chuẩn bị pre-production: budget, casting, wardrobe, timeline, crew',
            'Hỗ trợ đoàn sản xuất trong suốt quá trình quay',
            'Ghi chép footage, tiến độ quay & note của đạo diễn cho hậu kỳ',
          ],
          slides: 5,
          driveLink:      'https://youtu.be/cmKXtughTPE',
          driveLinkLabel: '↗ Xem video',
        },
        {
          id:    'p6',
          date:  '7/2023—28/1/2024',
          title: 'Short Film "Thực"',
          role:  'Producer, Behind The Scene',
          bullets: [
            'Lập & gửi call sheet hằng ngày',
            'Tuyển & quản lý diễn viên, quần chúng',
            'Hỗ trợ đạo diễn on-set, quản lý catering & location',
          ],
          slides: 5,
          driveLink:      'https://www.youtube.com/watch?v=PVonqvdKnzc',
          driveLinkLabel: '↗ Xem video',
        },
        {
          id:    'p7',
          date:  '12/2023—1/2024',
          title: 'Bona Media',
          role:  'Assistant Director',
          bullets: [
            'Hỗ trợ đạo diễn toàn diện trên set',
            'Quản lý booking & lịch trình diễn viên, crew',
            'Lập & phân phối call sheet, timeline sản xuất hằng ngày',
          ],
          slides: 5,
          driveLink:      'https://www.youtube.com/@BabyDollTVTiengViet',
          driveLinkLabel: '↗ Xem channel',
        },
        {
          id:    'p8',
          date:  '27/11—29/11/2023',
          title: 'Short Film "Chuộc"',
          role:  'Production Assistant, BTS, Runner',
          bullets: [
            'Ghi lại hình ảnh hoạt động & tương tác của đoàn phim',
            'Hỗ trợ on-set để đảm bảo sản xuất diễn ra trơn tru',
            '🏆 Award: Top 10 HUGFIA (HUTECH Graduation Film Award)',
          ],
          slides: 5,
          driveLink:      'https://www.youtube.com/watch?v=a5M-D0n5H-A',
          driveLinkLabel: '↗ Xem video',
        },
        {
          id:    'p9',
          date:  '25/11/2023',
          title: 'TVC Greenfeed',
          role:  'Production Assistant',
          bullets: [
            'Lập & phân phối call sheet hằng ngày',
            'Tuyển & quản lý diễn viên, quần chúng',
            'Hỗ trợ Producer & PA Leader trong vận hành on-set',
            'Setup & duy trì set design',
          ],
          slides: 5,
          driveLink:      'https://www.youtube.com/watch?v=2KTnTb8G8AY',
          driveLinkLabel: '↗ Xem video',
        },
        {
          id:    'p10',
          date:  '07/2023—12/2023',
          title: 'Short Film "Chữa Chết"',
          role:  'Producer',
          bullets: [
            'Lead pre-production planning cho toàn dự án',
            'Lập budget, casting, vendor & location coordination',
            'Quản lý nhân sự & nguồn lực tài chính cho sản xuất',
          ],
          slides: 5,
          driveLink:      'https://drive.google.com/file/d/1y3ds0YhfjJ4zgxffW_36WHqzbg1bVCE0/view?usp=drive_link',
          driveLinkLabel: '↗ View drive',
        },
        {
          id:    'p11',
          date:  '03/2023—05/2023',
          title: 'Short Film "Nơi Em Tìm Thấy Anh"',
          role:  'Script Writer, Producer, BTS',
          bullets: [
            'Phụ trách pre-production: phát triển kịch bản & lập kế hoạch dự án',
            'Viết & hoàn thiện kịch bản',
            'Xây dựng đối tác, fundraising cho dự án',
          ],
          slides: 5,
          driveLink:      'https://fb.watch/o386uwQvKz/',
          driveLinkLabel: '↗ Xem video',
        },
        {
          id:    'p12',
          date:  '03/2023—05/2023',
          title: 'Short Film "Má Bảy Của Tôi"',
          role:  'Behind The Scene, Set Support',
          bullets: [
            'Hỗ trợ logistics & hậu cần cho đạo diễn, diễn viên, crew khi quay',
            'Ghi lại hình ảnh behind-the-scene chất lượng cao',
          ],
          slides: 5,
          driveLink:      'https://www.youtube.com/watch?v=0pHAfruSbkQ',
          driveLinkLabel: '↗ Xem video',
        },
        {
          id:    'p13',
          date:  '03/2022—05/2022',
          title: 'Short Film "Tôi Ghét Ba"',
          role:  'Assistant Director, BTS',
          bullets: [
            'Đảm bảo sự thoải mái cho đạo diễn, diễn viên, crew trong suốt quá trình quay',
            'Rèn kỹ năng quản lý thời gian & nguồn lực, hỗ trợ đạo diễn',
            'Ghi lại hình ảnh behind-the-scene phục vụ truyền thông',
          ],
          slides: 5,
          driveLink:      'https://fb.watch/o3849ihxVw/',
          driveLinkLabel: '↗ Xem video',
        },
      ],
    },

    contact: {
      number:        '04',
      title:         'Liên Hệ',
      ctaLines:      ['Hãy cùng tạo ra', 'điều đáng xem.'],
      email:         'trangnguyn123@gmail.com',
      gmailUrl:      'https://mail.google.com/mail/?view=cm&fs=1&to=trangnguyn123@gmail.com',
      linkedinLabel: 'LinkedIn',
      linkedinUrl:   'https://www.linkedin.com/in/changg-nguyen/',
      location:      'Tại Tp. Hồ Chí Minh, VN',
    },

    footer: {
      copy: '© 2026 Changg Nguyễn',
      role: 'Content Creator · HCMC',
    },
  },
};
